@startuml
package "g12swe․rubrica" {

    class App

    package "controller" {
        class RootController
        class MainController
        class ContactController
    }

    package "model" {
        class AddressBook
        package "contacts" {
            abstract class Contact
            class BasicContact
            class ExtendedContact
            class PhoneNumber
            class EmailAddress
        }
    }
        
    package "view" {
        class RootView <<FXML>>
        class MainView <<FXML>>
        class ContactView <<FXML>>
    }

    package "validation" {
        abstract class Validatable
    }

    package "exceptions" {
        class InvalidPhoneNumberException
        class InvalidEmailAddressException
    }

    package "service" {
        abstract class AddressBookService
        class FileService
        class ImportExportService
    }

  
}

package "com․googlecode․ez-vcard" {
    class VCard
}




@enduml