@startuml

User -> MainView: addContactBtn
MainView -> MainController: AddContactEvent
MainController -> ContactController: addNewContact
ContactController -> Validatable: validateContact

alt Validation Failed
  Validatable -> MainController: validationFailed
  MainController -> MainView: showError("Invalid Contact")
else Validation Success
  Validatable -> VCard: convertContact
  VCard -> AddressBookService: saveToAddressBook
  
  alt Save Failed
    AddressBookService -> MainController: saveFailed
    MainController -> MainView: showError("Save Failed")
  else Save Success
    AddressBookService -> MainController: contactIsSaved
    MainController -> MainView: showMsg("Contact Saved!")
  end
end

@enduml
