@startuml

User  -> MainView: addContactBtn
MainView  -> MainController: AddContactEvent
ContactController-> AddressBook: addNewContact
AddressBook -> Validatable: validateContact
Validatable -> VCard: 
VCard -> AddressBookService: saveToAddressBook
AddressBookService -> MainController: contactIsSaved
MainController -> MainView: showMsg("Contact Saved!")

@enduml
