@startuml
User  -> View: addContact(datiContatto)
View   -> ContactController: addContact(datiContatto)
ContactController -> AddressBook: createContact(datiContatto)
AddressBook -> Contact: new Contact(datiContatto)
AddressBook -> AddressBookService: saveContact(Contact c)
AddressBookService -> ContactController: confirmSave()
ContactController -> View: showMsg("Contatto creato con successo")
View -> User: viewMsg("Contatto creato con successo")

@enduml
