@startuml
User -> MainView: selectImportFile()
MainView -> MainController: importContactListFromFile(filename)
MainController -> AddressBookService: importFile(filename)
AddressBookService -> ImportExportService: importFile(filename)
ImportExportService -> FileService: readFile()

alt File Not Valid
  FileService -> MainController: unreadableFile()
  MainController -> MainView: showErrMsg("File non leggibile")
  MainView -> User: viewErrMsg
else Valid File
  FileService --> ImportExportService: importedData (async)
  ImportExportService -> Validatable: validateData(importedData)
  Validatable -> ImportExportService: validationResult

  alt Contact Validation Failed
    ImportExportService -> MainController: ImportFailed
    MainController -> MainView: showErrMsg("Dati non validi")
    MainView -> User: viewErrMsg
  else Contact Validation Success
    ImportExportService -> VCard: convertContactFormat
    VCard -> ImportExportService: returnConvertedData
    ImportExportService -> AddressBook: importContacts
    AddressBook -> MainController: importConfirm
    MainController -> MainView: showMsg("importazione eseguita con successo")
    MainView -> User: viewMsg
  end
end
@enduml
