@startuml

User -> MainView: selectEditBtn
MainView -> MainController: editContactEvent
MainController -> MainView: showEditingForm
MainView -> User: viewEditingForm

User -> MainView: editContactDetails(newDetails)
MainView -> MainController: sendEditedContact(newDetails)
MainController -> Validatable: validateEditedContact(newDetails)

alt Validation Failed
  Validatable -> MainController: validationFailed
  MainController -> MainView: showError("Invalid Contact Details")
  MainView -> User: viewErrMsg  
else Validation Success
  Validatable -> MainController: contactIsValid
  MainController -> AddressBookService: updateContact(newDetails)  
alt Save Failed
  AddressBookService -> MainController: saveFailed
  MainController -> MainView: showErrMsg("Save Failed")
  MainView -> User: viewErrMsg
else Save Success
  AddressBookService -> MainController: contactIsSaved
  MainController -> MainView: showMsg("Contact Updated Successfully!")
  MainView -> User: viewMsg
end
end

@enduml
